import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Product from 'App/Models/Product'


export default class ProductSeeder extends BaseSeeder {
  public async run () {
    // seed products from json file
    await Product.createMany([
        {
          "code": "1214159",
          "suplier": "bunnings",
          "description": "ScotchBlue 36mm x 55m Original Multi-Surface Painter’s Masking Tape",
          "class": 1,
          "storage": 20,
          "min": 15,
          "max": 50,
          "place": 1,
          "price": 7
        },
        {
          "code": "0134810",
          "suplier": "bunnings",
          "description": "Mondella Resonance matte Black Pin Side Lever Sink Mixer",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 1091923,
          "suplier": "bunnings",
          "description": "Abey 25 x 0.8mm x 30m Punched Strapping",
          "class": 1,
          "storage": 2,
          "min": 3,
          "max": 8,
          "place": 1,
          "price": 48.8
        },
        {
          "code": "0267023",
          "suplier": "unknown",
          "description": "Euro Rangehood",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 1668203,
          "suplier": "bunnings",
          "description": "UNi-PRO 550mm x 25m Plastic Drop Down Sheet With Masking Tap",
          "class": 1,
          "storage": 4,
          "min": 3,
          "max": 6,
          "place": 1,
          "price": 5.27
        },
        {
          "code": " ",
          "suplier": "bunnings",
          "description": "UNi-PRO 2700mm x 17m Unimask Film with Masking Tape refill",
          "class": 1,
          "storage": 5,
          "min": 5,
          "max": 10,
          "place": 1,
          "price": 0
        },
        {
          "code": "0205455",
          "suplier": "bunnings",
          "description": "Mondella Concerto Rectangular Above Counter Basin",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0183046",
          "suplier": "unknown",
          "description": "EO604SX Euro oven",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "CPW615-XL",
          "suplier": "TRADETOOLS",
          "description": "Maxisafe White Polypropylene Disposable Coverall Overalls - Extra Large (XL) - CPW615-XL",
          "class": 1,
          "storage": 12,
          "min": 10,
          "max": 40,
          "place": 1,
          "price": 141.12
        },
        {
          "code": "0811087",
          "suplier": "bunnings",
          "description": "Builders Edge 100mm White Gravity Vent",
          "class": 1,
          "storage": 9,
          "min": 10,
          "max": 40,
          "place": 1,
          "price": 32
        },
        {
          "code": 5004133,
          "suplier": "bunnings",
          "description": "Mondella WELS 5 Star 6L/min Chrome Resonance Tall Pin Lever Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "?",
          "suplier": "unknown",
          "description": "Euro 7.5kg Front-Load Washer EFL75KWH",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5002872,
          "suplier": "bunnings",
          "description": "Mondella WELS 3 Star 9L/min 250mm Resonance Round Shower Head",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 121
        },
        {
          "code": 5103765,
          "suplier": "bunnings",
          "description": "5HOT WATER ALWAYS HOT DUX++17L 1 LPG CONT FLO 50DEG 17ENB5L",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 4440780,
          "suplier": "bunnings",
          "description": "Dynabreeze 600mm Black Industrial Drum Fan",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0811221",
          "suplier": "bunnings",
          "description": "Builders Edge 100mm Aluminium Weatherproof Louvre External Wall Vent",
          "class": 1,
          "storage": 0,
          "min": 0,
          "max": 10,
          "place": 1,
          "price": 32
        },
        {
          "code": 1370237,
          "suplier": "bunnings",
          "description": "Dulux 1Step Prep Primer, Sealer & Undercoat 15L",
          "class": 1,
          "storage": 6,
          "min": 3,
          "max": 9,
          "place": 1,
          "price": 150
        },
        {
          "code": "1660146",
          "suplier": "bunnings",
          "description": "UNi-PRO 100mm 9mm Nap Little Ripper High Density Foam Roller Cover - 10 Pack",
          "class": 1,
          "storage": 2,
          "min": 2,
          "max": 5,
          "place": 1,
          "price": 8.81
        },
        {
          "code": 130578,
          "suplier": "inspirations paint",
          "description": "DULUX DURAMAX METAL PRIMER 340G",
          "class": 1,
          "storage": 9,
          "min": 10,
          "max": 20,
          "place": 1,
          "price": 14.16
        },
        {
          "code": " 1667532",
          "suplier": "bunnings",
          "description": "Paint Partner 24mm x 27m Thick Masking Tape - 6 Pack",
          "class": 1,
          "storage": 1,
          "min": 0.5,
          "max": 3,
          "place": 1,
          "price": 3.7
        },
        {
          "code": "1yhrv",
          "suplier": "unknown",
          "description": "Tiny houses sign",
          "class": 1,
          "storage": 50,
          "min": 15,
          "max": 50,
          "place": 1,
          "price": 0
        },
        {
          "code": 5004149,
          "suplier": "bunnings",
          "description": "Mondella WELS 4 Star 7.5L/min Chrome Maestro Lever Handle Sink Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 2760578,
          "suplier": "bunnings",
          "description": "Montgomery 1830 x 910 x 410mm 5 Tier Shelving Unit",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 2610071,
          "suplier": "bunnings",
          "description": "Wrap & Move 500mm x 280m Clear Pallet Shrink Wrap",
          "class": 4,
          "storage": 1,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 5
        },
        {
          "code": "0198172",
          "suplier": "bunnings",
          "description": "Estilo 450mm Vanity With Semi-Recessed Basin And 1 Tap Hole",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0266932",
          "suplier": "unknown",
          "description": "Euro 30cm Gas Cooktop ECT30GX",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "1n6ii",
          "suplier": "unknown",
          "description": "ULTRABOND ECO MS 4 LVT WALL (floor glue)",
          "class": 1,
          "storage": 16,
          "min": 10,
          "max": 20,
          "place": 1,
          "price": 150
        },
        {
          "code": "0134813",
          "suplier": "bunnings",
          "description": "Mondella WELS 4 Star 7.5L/min Matte Black Resonance Wall Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 4700441,
          "suplier": "bunnings",
          "description": "Pacific Air 150mm Aluminium Weatherproof Louvre Vent",
          "class": 2,
          "storage": 10,
          "min": 20,
          "max": 50,
          "place": 1,
          "price": 55
        },
        {
          "code": "0860405",
          "suplier": "bunnings",
          "description": "Gorilla 175kg Industrial Safety Step",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0029077",
          "suplier": "bunnings",
          "description": "Ametalin 72mm x 50m Reinforced Insulation / Ducting Tape",
          "class": 2,
          "storage": 2,
          "min": 20,
          "max": 50,
          "place": 1,
          "price": 25.67
        },
        {
          "code": 185481,
          "suplier": "inspirations paint",
          "description": "DULUX WEATHERSHIELD LOW SHEEN MONUMENT 10L",
          "class": 2,
          "storage": 3,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 239
        },
        {
          "code": "169864 - \n9300611591494",
          "suplier": "inspirations paint",
          "description": "INTERGRAIN ULTRACLEAR EXTERIOR TIMBER FINISH MATT 10L",
          "class": 2,
          "storage": 1,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 327.75
        },
        {
          "code": 2360675,
          "suplier": "bunnings",
          "description": "Paslode 32 x 2.5mm Electro Galvanised Screw Hardened 15 Degree Pneumatic Plastic Collated Coil Nails - 3600 Pack",
          "class": 2,
          "storage": 3,
          "min": 1,
          "max": 2,
          "place": 1,
          "price": 0
        },
        {
          "code": "0811086",
          "suplier": "bunnings",
          "description": "Builders Edge 150mm White Grill Vent with Insect Screen",
          "class": 2,
          "storage": 22,
          "min": 10,
          "max": 50,
          "place": 1,
          "price": 11.13
        },
        {
          "code": "0144254",
          "suplier": "bunnings",
          "description": "Bear 48mm x 50m Interior Decorator Masking Tape",
          "class": 2,
          "storage": 20,
          "min": 10,
          "max": 40,
          "place": 1,
          "price": 7
        },
        {
          "code": 1560239,
          "suplier": "bunnings",
          "description": "UNi-PRO 100mm Little Ripper Microfibre Mini Roller Covers 10 Pack 10mm Nap",
          "class": 2,
          "storage": 5,
          "min": 2,
          "max": 5,
          "place": 1,
          "price": 11.61
        },
        {
          "code": "0811083",
          "suplier": "bunnings",
          "description": "Builders Edge 2.4m x 100mm Aluminium Foil Flexible Duct",
          "class": 2,
          "storage": 11,
          "min": 10,
          "max": 20,
          "place": 1,
          "price": 17
        },
        {
          "code": "1834",
          "suplier": "HiPAC",
          "description": "HT Glass Protection - 1220mm x 100m x 70um Green",
          "class": 2,
          "storage": 1,
          "min": 1,
          "max": 2,
          "place": 1,
          "price": 236.5
        },
        {
          "code": 118082,
          "suplier": "inspirations paint",
          "description": "PORTER'S PAINTS LOW SHEEN ACRYLIC CLEAR 4L",
          "class": 2,
          "storage": 1,
          "min": 1,
          "max": 2,
          "place": 1,
          "price": 0
        },
        {
          "code": "0287733",
          "suplier": "bunnings",
          "description": "Ozito Lawn Mower",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 185460,
          "suplier": "inspirations paint",
          "description": "DULUX WEATHERSHIELD LOW SHEEN VIVID WHITE 15L",
          "class": 2,
          "storage": 3,
          "min": 3,
          "max": 6,
          "place": 1,
          "price": 0
        },
        {
          "code": 4814525,
          "suplier": "unknown",
          "description": "Kingspan 4000l Slim Steel Watertank",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0123798",
          "suplier": "bunnings",
          "description": "Fusion Loc Suction Frosted Acrylic Bathroom Shelf",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0130092",
          "suplier": "bunnings",
          "description": "Caroma Cosmo Toilet Roll Holder",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 185486,
          "suplier": "inspirations paint",
          "description": "DULUX WEATHERSHIELD LOW SHEEN BLACK 10L",
          "class": 2,
          "storage": 1,
          "min": 1,
          "max": 2,
          "place": 1,
          "price": 198.46
        },
        {
          "code": "0181395",
          "suplier": "bunnings",
          "description": "Mondella Rococo 3 Door Mirrored Shaving Cabinet",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "125",
          "suplier": "unknown",
          "description": "Stylus Verdi Sink Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5090441,
          "suplier": "bunnings",
          "description": "Mondella Resonance Single Bowl Round Stainless Steel Sink",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0000076",
          "suplier": "unknown",
          "description": "Skylight Accessoire short winder handle",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0134814",
          "suplier": "bunnings",
          "description": "Mondella WELS 4 Star 7.5L/min Chrome Resonance Wall Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0046946",
          "suplier": "bunnings",
          "description": "Accord 5 x 30cm White Metal Kick Rail Vent",
          "class": 2,
          "storage": 39,
          "min": 10,
          "max": 50,
          "place": 1,
          "price": 9.98
        },
        {
          "code": "BPWFP100",
          "suplier": "aerofast",
          "description": "PACKERS 10MM X 75MM",
          "class": 4,
          "storage": 2,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 50.02
        },
        {
          "code": 3060,
          "suplier": "total tools",
          "description": "TREFOLEX 500ML TREFOLEX CUTTING PASTE",
          "class": 4,
          "storage": 2,
          "min": 1,
          "max": 5,
          "place": 1,
          "price": 34
        },
        {
          "code": "BPWFP16",
          "suplier": "aerofast",
          "description": "PACKERS 1.6MM X 75MM",
          "class": 4,
          "storage": 1,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 28.92
        },
        {
          "code": "BPWFP32",
          "suplier": "aerofast",
          "description": "PACKERS 3.2MM X 75MM",
          "class": 4,
          "storage": 1,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 32.48
        },
        {
          "code": "BPWFP50",
          "suplier": "aerofast",
          "description": "PACKERS 5.0MM X 75MM",
          "class": 4,
          "storage": 0,
          "min": 1,
          "max": 3,
          "place": 1,
          "price": 32.8
        },
        {
          "code": "4bbgj",
          "suplier": "unknown",
          "description": "mud guard ",
          "class": 4,
          "storage": 110,
          "min": 100,
          "max": 300,
          "place": 1,
          "price": 0
        },
        {
          "code": "4xb85",
          "suplier": "bunker",
          "description": "Subflooring 19mm plywood 1 sheet ",
          "class": 1,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "265kt",
          "suplier": "bunker",
          "description": "EASY CLAD 150MM ",
          "class": 1,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0281241",
          "suplier": "unknown",
          "description": "Smart Home Products 40 x 60cm Black Rubber/Polypropylene Mat",
          "class": 3,
          "storage": 5,
          "min": 5,
          "max": 50,
          "place": 1,
          "price": 5
        },
        {
          "code": "0171328",
          "suplier": "bunnings",
          "description": "Firepro 1kg Dry Powder Fire Extinguisher",
          "class": 3,
          "storage": 5,
          "min": 10,
          "max": 30,
          "place": 1,
          "price": 20
        },
        {
          "code": "0237501",
          "suplier": "bunnings",
          "description": "Lane Matte Black SR Privacy Cavity Slider",
          "class": 3,
          "storage": 12,
          "min": 10,
          "max": 30,
          "place": 1,
          "price": 29.98
        },
        {
          "code": 165684,
          "suplier": "bunnings",
          "description": "Lane Gun Metal Cavity Slider SR Privacy",
          "class": 3,
          "storage": 0,
          "min": 5,
          "max": 10,
          "place": 1,
          "price": 30.01
        },
        {
          "code": "4hnpm",
          "suplier": "unknown",
          "description": "Insubreke type  (cladding tape)",
          "class": 1,
          "storage": 3,
          "min": 5,
          "max": 7,
          "place": 1,
          "price": 283.63
        },
        {
          "code": "2olof",
          "suplier": "unknown",
          "description": "rug 10 kg",
          "class": 1,
          "storage": 0,
          "min": 2,
          "max": 10,
          "place": 4,
          "price": 51.82
        },
        {
          "code": "urnq",
          "suplier": "unknown",
          "description": "methe",
          "class": 3,
          "storage": 0,
          "min": 1,
          "max": 3,
          "place": 4,
          "price": 0
        },
        {
          "code": "mln9",
          "suplier": "unknown",
          "description": "acetone",
          "class": 3,
          "storage": 2,
          "min": 1,
          "max": 3,
          "place": 4,
          "price": 175.5
        },
        {
          "code": "sm1e",
          "suplier": "unknown",
          "description": "turpine",
          "class": 3,
          "storage": 3,
          "min": 1,
          "max": 3,
          "place": 4,
          "price": 120
        },
        {
          "code": "EC9012",
          "suplier": "bunnings (Designer Bathrooms)",
          "description": "Oceano Stonelite Eco Showerbase 900 x 1200",
          "class": 1,
          "storage": 15,
          "min": 5,
          "max": 20,
          "place": 6,
          "price": 380
        },
        {
          "code": "1ovk9",
          "suplier": "bunker",
          "description": "Plywood Flooring 2400 x 1200 x 12mm (roof)",
          "class": 1,
          "storage": 10,
          "min": 15,
          "max": 30,
          "place": 6,
          "price": 62
        },
        {
          "code": "6661043",
          "suplier": "bunnings",
          "description": "WALL PANEL WET AREA 3MM LINEAR++2400X1200X3MM NEW YORK WHITE",
          "class": 1,
          "storage": 20,
          "min": 40,
          "max": 90,
          "place": 6,
          "price": 180
        },
        {
          "code": "1synt",
          "suplier": "bunker",
          "description": "Plywood Flooring 2400 x 1200 x 15mm (loft floor).",
          "class": 1,
          "storage": 6,
          "min": 20,
          "max": 160,
          "place": 6,
          "price": 62
        },
        {
          "code": "2zap5",
          "suplier": "bunker",
          "description": "Easy VJ PR MR T&G 100C 3600X1200 x 9.0mm(VJ board 3.6)",
          "class": 1,
          "storage": 8,
          "min": 90,
          "max": 120,
          "place": 6,
          "price": 99.82
        },
        {
          "code": "0340054",
          "suplier": "bunnings",
          "description": "2440 x 900mm 4mm Braceboard F22 Plywood Hardwood",
          "class": 2,
          "storage": 22,
          "min": 5,
          "max": 20,
          "place": 6,
          "price": 55
        },
        {
          "code": "1u29d",
          "suplier": "bunker",
          "description": "PVC  Shower panel joints 3mm",
          "class": 1,
          "storage": 23,
          "min": 20,
          "max": 50,
          "place": 7,
          "price": 162
        },
        {
          "code": "1lo37",
          "suplier": "unknown",
          "description": "roof battons 6040mm x  40 mm",
          "class": 1,
          "storage": 90,
          "min": 20,
          "max": 50,
          "place": 7,
          "price": 22
        },
        {
          "code": "0714174",
          "suplier": "bunnings",
          "description": "FC LINING VILLABOARD 6MM JH++2400X1200MM 2.88SQM 400362",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "2g2z7",
          "suplier": "unknown",
          "description": "roof battons 6040mm x 60 mm",
          "class": 1,
          "storage": 20,
          "min": 5,
          "max": 20,
          "place": 7,
          "price": 21
        },
        {
          "code": "0020783",
          "suplier": "bunnings",
          "description": "PINE DAR FJ PENCIL ROUND CLEAR 112 x 18 x 5.4m EDGE",
          "class": 2,
          "storage": 0,
          "min": 25,
          "max": 60,
          "place": 7,
          "price": 22.28
        },
        {
          "code": 8032162,
          "suplier": "bunnings",
          "description": "90 x 45mm L/M Outdoor Framing MGP10 H3 Treated Pine 5950 MM",
          "class": 2,
          "storage": 28,
          "min": 20,
          "max": 50,
          "place": 7,
          "price": 0
        },
        {
          "code": 8030920,
          "suplier": "bunnings",
          "description": "240 x 45mm 4840 mm Framing MGP10 Untreated Pine",
          "class": 2,
          "storage": 8,
          "min": 2,
          "max": 5,
          "place": 7,
          "price": 0
        },
        {
          "code": "0021266",
          "suplier": "bunnings",
          "description": "PINE PRIMED DAR FJ 92 x 11 x 5.4m",
          "class": 2,
          "storage": 13,
          "min": 10,
          "max": 30,
          "place": 7,
          "price": 21.2
        },
        {
          "code": "0021147",
          "suplier": "bunnings",
          "description": "66 x 11mm 5.4m Moulding White Pine FJ Primed DAR",
          "class": 2,
          "storage": 6,
          "min": 30,
          "max": 40,
          "place": 7,
          "price": 13.74
        },
        {
          "code": "5004139",
          "suplier": "bunnings",
          "description": "Mondella WELS 5 Star 6L/min Chrome Resonance Pin Side Lever Sink Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 129.9
        },
        {
          "code": 5003404,
          "suplier": "bunnings",
          "description": "Methven WELS 4 Star 7.5L/min Chrome Gaston Pull Down Sink Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5003308,
          "suplier": "bunnings",
          "description": "Estilo WELS 4 Star 7.5L/min Chrome Pin Lever Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 37.54
        },
        {
          "code": 5004136,
          "suplier": "bunnings",
          "description": "Mondella WELS 5 Star 6L/min Chrome Resonance Pin Lever Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004137,
          "suplier": "bunnings",
          "description": "Mondella WELS 5 Star 6L/min Resonance Matte Black Pin Lever Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004134,
          "suplier": "bunnings",
          "description": "Mondella WELS 5 Star 6L/min Black Resonance Tall Pin Lever Basin Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5003293,
          "suplier": "bunnings",
          "description": "Mondella 40mm Chrome Resonance Pin Lever Shower Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5003295,
          "suplier": "bunnings",
          "description": "Mondella Rococo Shower Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004306,
          "suplier": "bunnings",
          "description": "Mondella Black Resonance Pin Lever Shower Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5002959,
          "suplier": "bunnings",
          "description": "Mondella Chrome Resonance Pin Lever Diverter Bath And Shower Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004307,
          "suplier": "bunnings",
          "description": "Mondella Black Resonance Diverter Shower Mixer",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004187,
          "suplier": "bunnings",
          "description": "Mondella Black Resonance Pin Lever Wall Top Assembly",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0128275",
          "suplier": "bunnings",
          "description": "MIXX Anise 180mm Matt Black Wall Basin Spout",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004272,
          "suplier": "bunnings",
          "description": "Mondella WELS 3 Star 9L/min 250mm Rococo Rain Square Shower Head",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5004270,
          "suplier": "bunnings",
          "description": "Mondella WELS 3 Star 9L/min 250mm Black Resonance Rain Shower Head",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5003335,
          "suplier": "bunnings",
          "description": "Mondella WELS 3 Star 9L/min Chrome Rumba 5 Function Hand Shower",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 5003336,
          "suplier": "bunnings",
          "description": "Mondella WELS 3 Star 9L/Min Matt Black Vivace 5 Function Hand Shower",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 4844201,
          "suplier": "bunnings",
          "description": "Wall Hung Vanity - White - 1 Tap Hole 400x580x220mm",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 4844040,
          "suplier": "unknown",
          "description": "450 x 350 x 860mm semi recessed freestanding vanity set",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 4843753,
          "suplier": "bunnings",
          "description": "Forme White Organic Oval Counter Top Basin",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 108
        },
        {
          "code": 4823163,
          "suplier": "bunnings",
          "description": "Stylus WELS 4 Star, 4.5L/Min Prima Connector S Trap Toilet Suite",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "703.254.25",
          "suplier": "ikea",
          "description": "LILLVIKEN Strainers",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "393.965.66",
          "suplier": "ikea",
          "description": "Enhet Mirror Cabinet 2 door",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "804.287.05",
          "suplier": "ikea",
          "description": "STORAVAN Toilet Brush",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "392.783.08",
          "suplier": "ikea",
          "description": "KALLAX Shelving unit with 4 inserts",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "802.723.46",
          "suplier": "ikea",
          "description": "MOSHULT Foam mattress, firm/white Queen",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "292.537.75",
          "suplier": "ikea",
          "description": "Havsen Sinks + Stainers",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "802.787.15",
          "suplier": "ikea",
          "description": "LÖNSET Slatted bed base Queen ",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "193.965.72",
          "suplier": "ikea",
          "description": "ENHET Mirror cabinet with 2 doors",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "693.965.60",
          "suplier": "ikea",
          "description": "Enhet Mirror cabinet with 1 door",
          "class": 5,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 603101312,
          "suplier": "aerofast",
          "description": "14 x 75 T17 Bugle Batten Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 603101605,
          "suplier": "aerofast",
          "description": "14 x 100 T17 Bugle Batten Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603101312MP",
          "suplier": "aerofast",
          "description": "14 x 75 T17 Bugle Batten C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603101605MP",
          "suplier": "aerofast",
          "description": "14 x 100 T17 Bugle Batten C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "6T17SQDCS1065",
          "suplier": "aerofast",
          "description": "10-8 x 65 T17 Sq/Drive Csk Rib 304 STST",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "6T4XGXRQ1016050",
          "suplier": "aerofast",
          "description": "10-16 x 50 Square Drive Wingtek 304 STST(Bulk Buy)",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "STCSXSQ0845",
          "suplier": "aerofast",
          "description": "8 x 1-3/4 Csk Self Tapping Screw Sq/Drive 304 STST",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101016,
          "suplier": "aerofast",
          "description": "8-10 x 25 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101032,
          "suplier": "aerofast",
          "description": "8-10 x 40 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101067,
          "suplier": "aerofast",
          "description": "8-10 x 57 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101102,
          "suplier": "aerofast",
          "description": "10-8 x 65 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101091,
          "suplier": "aerofast",
          "description": "10-8 x 75 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 624101207,
          "suplier": "aerofast",
          "description": "10-8 x 100 Chipboard Z/Y",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "624102037MP",
          "suplier": "aerofast",
          "description": "8-15 x 20 Button N/Pt C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "624102021MP",
          "suplier": "aerofast",
          "description": "8-15 x 30 Button N/Pt C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603101501MP",
          "suplier": "aerofast",
          "description": "10-12 x 35 T17 Wafer C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "631101506MP",
          "suplier": "aerofast",
          "description": "10-16 x 16 Wafer Tek C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "631137722C4",
          "suplier": "aerofast",
          "description": "M4.8-18 x 25 Fibre Tek C4",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "632100407CC",
          "suplier": "aerofast",
          "description": "10-16 x 45 Csk Rib Wingtek Climacoat",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "STPNXS1030",
          "suplier": "aerofast",
          "description": "10 x 1-1/4 Pan Self Tapping Screw 304 STST",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "STPNXS1065",
          "suplier": "aerofast",
          "description": "10 x 2-1/2 Pan Self Tapping Screw 304 STST",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "631100759CS",
          "suplier": "aerofast",
          "description": "12-14 x 35 Hex Tek Bare C3",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "S46MG101202",
          "suplier": "aerofast",
          "description": "M10 X 120 Hex Set Screw Gr4.6 Galv",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "S46MG101502",
          "suplier": "aerofast",
          "description": "M10 x 150 Hex Set Screw Gr4.6 Galv",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "CYCSQ38103HDG",
          "suplier": "aerofast",
          "description": "38 x 38 x 3 x M10 Sq Washer Galv",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "N46MG1000N2",
          "suplier": "aerofast",
          "description": "M10 Hex Nut Galv",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "BPEBSTST10120",
          "suplier": "aerofast",
          "description": "EYE BOLT M10 X 110",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43",
          "suplier": "aerofast",
          "description": "Rivet 43 Aluminium",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS45",
          "suplier": "aerofast",
          "description": "Rivet 4-5 Aluminium",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS48",
          "suplier": "aerofast",
          "description": "Rivet 4-8 Aluminium",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS54",
          "suplier": "aerofast",
          "description": "Rivet 5-4 Aluminium",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "NBT100-25",
          "suplier": "aerofast",
          "description": "Trim Brad 25mm Strip (3000 Box)",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "NBT150-38",
          "suplier": "aerofast",
          "description": "Trim Brad 38mm Strip (1500 Box)",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0020887",
          "suplier": "bunnings",
          "description": "42 x 11mm 5.4m Moulding White Pine FJ Primed DAR",
          "class": 2,
          "storage": 250,
          "min": 100,
          "max": 200,
          "place": 7,
          "price": 13.74
        },
        {
          "code": "0020749",
          "suplier": "bunnings",
          "description": "Woodhouse EdgeLine 42 x 18mm 5.4m DAR Primed Finger Jointed Pine Moulding",
          "class": 2,
          "storage": 4,
          "min": 20,
          "max": 60,
          "place": 7,
          "price": 10
        },
        {
          "code": "0020817",
          "suplier": "bunnings",
          "description": "31 x 31mm x 5.4m Clear Pine Finger Jointed External Corner Moulding",
          "class": 2,
          "storage": 37,
          "min": 30,
          "max": 80,
          "place": 7,
          "price": 11
        },
        {
          "code": "603033072C4OW",
          "suplier": "aerofast",
          "description": "M6 x 65 Roof Zip+Seal C4 - Surfmist",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033072C4GM",
          "suplier": "aerofast",
          "description": "M6 x 65 Roof Zip+Seal C4 - Monument",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033072C4BA",
          "suplier": "aerofast",
          "description": "M6 x 65 Roof Zip+Seal C4 - Basalt",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033072C4BI",
          "suplier": "aerofast",
          "description": "M6 x 65 Roof Zip+Seal C4 - Dune",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033072C4SG",
          "suplier": "aerofast",
          "description": "M6 x 65 Roof Zip+Seal C4 - Woodland Grey",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033268C4BA",
          "suplier": "aerofast",
          "description": "M5-16 x 25 Designer Head +Seal C4 - Basalt",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033268C4GM",
          "suplier": "aerofast",
          "description": "M5-16 x 25 Designer Head +Seal C4 - Monument",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "603033268C4OW",
          "suplier": "aerofast",
          "description": "M5-16 x 25 Designer Head +Seal C4 - Surfmist",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43BA",
          "suplier": "aerofast",
          "description": "Rivet 4-3 Aluminium - Basalt",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43BI",
          "suplier": "aerofast",
          "description": "Rivet 4-3 Aluminium - Dune",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43MO",
          "suplier": "aerofast",
          "description": "Rivet 4-3 Aluminium - Monument",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43OW",
          "suplier": "aerofast",
          "description": "Rivet 4-3 Aluminium - Surfmist",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "RAS43WA",
          "suplier": "aerofast",
          "description": "Rivet 4-3 Aluminium - Wallaby",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "ADPRGPTRANS",
          "suplier": "aerofast",
          "description": "Bostik R&G 100% Silicone - Translucent",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "ADPRGPGREY",
          "suplier": "aerofast",
          "description": "Bostik R&G 100% Silicone - Grey",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "ADPRGPMO",
          "suplier": "aerofast",
          "description": "Bostik R&G 100% Silicone - Monument",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "ADPRGPSM",
          "suplier": "aerofast",
          "description": "Bostik R&G 100% Silicone - Surfmist",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "ADPRGPWG",
          "suplier": "aerofast",
          "description": "Bostik R&G 100% Silicone - Woodland Grey",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "AD6SCL",
          "suplier": "aerofast",
          "description": "Bostik 6S Silicone Sanitary & Tile - Translucent",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "AD1120",
          "suplier": "aerofast",
          "description": "Bostik Seal & Flex ADVANCE Sausage - Grey",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "AD0120",
          "suplier": "aerofast",
          "description": "Bostik UltraSet Sausage SF - Flooring Adhesive",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 1070480,
          "suplier": "bunnings",
          "description": "Moroday 6mm x 100m MGF3 Gap Filler Rod",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "53vot",
          "suplier": "unknown",
          "description": "PINE DAR FJ primed ++11X11MM 5.4M",
          "class": 2,
          "storage": 330,
          "min": 50,
          "max": 200,
          "place": 7,
          "price": 5.16
        },
        {
          "code": 8031407,
          "suplier": "unknown",
          "description": "PINE STRUCTURAL MGP12 BLUE H2++90X35MM L/M 4.8M-6.0M",
          "class": 2,
          "storage": 42,
          "min": 10,
          "max": 20,
          "place": 7,
          "price": 0
        },
        {
          "code": "25fru",
          "suplier": "unknown",
          "description": "aluminium 25 x 25 1.6 not primed",
          "class": 1,
          "storage": 20,
          "min": 10,
          "max": 20,
          "place": 7,
          "price": 16.819
        },
        {
          "code": "21er0",
          "suplier": "unknown",
          "description": "aluminium 9 x 9  1.6  primed white",
          "class": 1,
          "storage": 5,
          "min": 5,
          "max": 10,
          "place": 7,
          "price": 46
        },
        {
          "code": "50bwn",
          "suplier": "unknown",
          "description": "aluminium 25 x 25 1.6 primed white",
          "class": 1,
          "storage": 23,
          "min": 5,
          "max": 10,
          "place": 7,
          "price": 23.5
        },
        {
          "code": 1563594,
          "suplier": "bunnings",
          "description": "Timbermate 250g Hardwood Wood Filler",
          "class": 4,
          "storage": 4,
          "min": 2,
          "max": 4,
          "place": 1,
          "price": 9.21
        },
        {
          "code": " 1560902",
          "suplier": "bunnings",
          "description": "Timbermate Cedar 250g",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "1571642",
          "suplier": "bunnings",
          "description": "Timbermate 250g Brush Box Wood Filler",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "1560708",
          "suplier": "bunnings",
          "description": "Timbermate 250g Walnut Wood Filler",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 1580110,
          "suplier": "bunnings",
          "description": "Waxstix Baltic Pine Timbermate Touch Up Crayon",
          "class": 4,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1130530",
          "suplier": "bunnings",
          "description": "Pryda Strap Brace Tensioner And Bolt - 30 Box",
          "class": 1,
          "storage": 4,
          "min": 12,
          "max": 60,
          "place": 7,
          "price": 2.63
        },
        {
          "code": "l25a",
          "suplier": "bunker",
          "description": "cedar cut off",
          "class": 2,
          "storage": 50,
          "min": 0,
          "max": 50,
          "place": 9,
          "price": 5
        },
        {
          "code": "0020740",
          "suplier": "bunnings",
          "description": "Woodhouse Weatherproof 92 x 18mm 5.4m DAR PR4 H3 LOSP Treated And Primed Finger Jointed Pine Moulding",
          "class": 2,
          "storage": 6,
          "min": 10,
          "max": 20,
          "place": 10,
          "price": 0
        },
        {
          "code": "0052846",
          "suplier": "bunnings",
          "description": "PINE TREATED F7 FJ LOSP H3++66X30MM 5.4M RADIATA PRIMED",
          "class": 2,
          "storage": 0,
          "min": 5,
          "max": 10,
          "place": 10,
          "price": 0
        },
        {
          "code": 2012188,
          "suplier": "bunnings",
          "description": "Hume Primecoat Honeycomb Flush Door - 2040mm x 720mm x 35mm",
          "class": 1,
          "storage": 7,
          "min": 20,
          "max": 40,
          "place": 10,
          "price": 42.91
        },
        {
          "code": "0052820",
          "suplier": "bunnings",
          "description": "180 x 25mm 5.4m Fascia H3 Treated Pine Primed LOSP",
          "class": 3,
          "storage": 2,
          "min": 0,
          "max": 2,
          "place": 10,
          "price": 55
        },
        {
          "code": 2035938,
          "suplier": "bunnings",
          "description": "Hume 2040 x 720 x 70mm Evolution Fj Flush Jamb Door Cavity Unit",
          "class": 1,
          "storage": 5,
          "min": 5,
          "max": 10,
          "place": 13,
          "price": 81
        },
        {
          "code": "1wns4",
          "suplier": "unknown",
          "description": "aluminium 32 x 20 1.6 not primed",
          "class": 1,
          "storage": 1,
          "min": 5,
          "max": 10,
          "place": 13,
          "price": 16.8
        },
        {
          "code": "1w1w4",
          "suplier": "unknown",
          "description": "cover sheet ",
          "class": 1,
          "storage": 37,
          "min": 15,
          "max": 50,
          "place": 13,
          "price": 93.83
        },
        {
          "code": "nsxt",
          "suplier": "unknown",
          "description": "cover sheet havy duty",
          "class": 1,
          "storage": 5,
          "min": 2,
          "max": 5,
          "place": 13,
          "price": 95.83
        },
        {
          "code": "EC820R",
          "suplier": "bunnings (Designer Bathrooms)",
          "description": " Oceano Stonelite Eco Showerbase 820 x 820",
          "class": 1,
          "storage": 17,
          "min": 5,
          "max": 20,
          "place": 13,
          "price": 245
        },
        {
          "code": "44a8y",
          "suplier": "unknown",
          "description": "aluminium 32 x 20 1.6 primed white",
          "class": 1,
          "storage": 1,
          "min": 2,
          "max": 5,
          "place": 13,
          "price": 23.562
        },
        {
          "code": "kvzd",
          "suplier": "unknown",
          "description": "aluminium 40 x 40 1.6 not primed",
          "class": 2,
          "storage": 10,
          "min": 3,
          "max": 5,
          "place": 13,
          "price": 0
        },
        {
          "code": "0820123",
          "suplier": "bunnings",
          "description": "Skylight VCM 572 x 876",
          "class": 1,
          "storage": 4,
          "min": 3,
          "max": 8,
          "place": 13,
          "price": 1700
        },
        {
          "code": "0110996",
          "suplier": "unknown",
          "description": "Primed Pine H3 Dar",
          "class": 2,
          "storage": 0,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "??",
          "suplier": "bunnings",
          "description": "DAR Finger Jointed Pine",
          "class": 2,
          "storage": 0,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 8030966,
          "suplier": "bunnings",
          "description": "TRIM70X45MM 4.8M TREATED AND SMOOTH FACE",
          "class": 2,
          "storage": 0,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": 3981190,
          "suplier": "bunnings",
          "description": "Rolltrak Cavity Door Guide",
          "class": 2,
          "min": 0,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": "0028404",
          "suplier": "bunnings",
          "description": "Skylight VCS 648 x 952",
          "class": 1,
          "storage": 2,
          "min": 3,
          "max": 8,
          "place": 13,
          "price": 1700
        },
        {
          "code": "0810603",
          "suplier": "unknown",
          "description": "Earthwool Insulation 2.5",
          "class": 1,
          "storage": 144,
          "min": 20,
          "max": 60,
          "place": 14,
          "price": 75.76
        },
        {
          "code": "15e7k",
          "suplier": "bunker",
          "description": "90 mm x 45mm x 3660 mm not treated timber",
          "class": 2,
          "storage": 0,
          "min": 40,
          "max": 120,
          "place": 16,
          "price": 0
        },
        {
          "code": "k8f8",
          "suplier": "bunker",
          "description": "cedar 2480x 180",
          "class": 2,
          "storage": 60,
          "min": 50,
          "max": 100,
          "place": 16,
          "price": 17.74
        },
        {
          "code": "2pidu",
          "suplier": "unknown",
          "description": "acrilic Sheet ",
          "class": 1,
          "storage": 7,
          "min": 5,
          "max": 20,
          "place": 17,
          "price": 0
        },
        {
          "code": "0820096",
          "suplier": "bunnings",
          "description": "Velux Short Winder Handles ZZZ 201",
          "class": 4,
          "storage": 20,
          "min": 15,
          "max": 30,
          "place": 18,
          "price": 42
        },
        {
          "code": 1560362,
          "suplier": "bunnings",
          "description": "Loctite 243 10ml Adhesive Threadlocker",
          "class": 1,
          "storage": 5,
          "min": 3,
          "max": 10,
          "place": 18,
          "price": 12.89
        },
        {
          "code": 2035935,
          "suplier": "bunnings",
          "description": "Hume 2040 x 720 x 90mm Evolution Flush Pull Door Cavity Unit",
          "class": 1,
          "storage": 5,
          "min": 10,
          "max": 30,
          "place": 19,
          "price": 173.4
        },
        {
          "code": "3yxn",
          "suplier": "bunker",
          "description": "cedar 4280x 180",
          "class": 2,
          "storage": 288,
          "min": 100,
          "max": 300,
          "place": 20,
          "price": 17.74
        },
        {
          "code": "1edqq",
          "suplier": "bunker",
          "description": "cedar 3600x 180",
          "class": 2,
          "storage": 0,
          "min": 50,
          "max": 100,
          "place": 20,
          "price": 0
        },
        {
          "code": "0020753",
          "suplier": "bunnings",
          "description": "138 x 18mm 5.4m Moulding White Pine FJ Primed DAR",
          "class": 3,
          "storage": 9,
          "min": 20,
          "max": 40,
          "place": "7 AND 10",
          "price": 55
        },
        {
          "code": "1544880 ",
          "suplier": "Reece",
          "description": "Evopex Straight Coupling 16mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": "1544887 ",
          "suplier": "Reece",
          "description": "Evopex Elbow 16mm 1.00 EA ",
          "class": 1,
          "min": 20,
          "max": 40,
          "place": 0,
          "price": 0
        },
        {
          "code": "1544899 ",
          "suplier": "Reece",
          "description": "Evopex Tee 16mm 1.00 EA ",
          "class": 1,
          "min": 20,
          "max": 40,
          "place": 0,
          "price": 0
        },
        {
          "code": "1544894 ",
          "suplier": "Reece",
          "description": "Evopex 19bp Elbow (100) 16mm X 1/2\" MI 1.00 EA ",
          "class": 1,
          "min": 20,
          "max": 40,
          "place": 0,
          "price": 0
        },
        {
          "code": "1544883 ",
          "suplier": "Reece",
          "description": "Evopex Straight Connector MI 16x1/2\" Bsp 1.00 EA ",
          "class": 1,
          "min": 8,
          "max": 16,
          "place": 0,
          "price": 0
        },
        {
          "code": "1545192 ",
          "suplier": "Reece",
          "description": "Evopex Elbow 16mm X 1/2\"mi 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1544001",
          "suplier": "Reece",
          "description": " Evopex 16mmx15mm B-Press Copper Adaptors 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1544904",
          "suplier": "Reece",
          "description": " Evopex Stop End 16mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 505892 ",
          "suplier": "Reece",
          "description": "Copper Saddle Heavy 15mm 1.00 EA ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 505893 ",
          "suplier": "Reece",
          "description": "Copper Saddle Heavy 20mm 1.00 EA ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403120",
          "suplier": "Reece",
          "description": " Dwv Bend 50 X 85 Deg Plain 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 9504607",
          "suplier": "Reece",
          "description": " Ardent Scrwd Outlet 15x150 900 Tail 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 106988 ",
          "suplier": "Reece",
          "description": "Fitquik 2 Cistern Stop 15mm Cone&Nut 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1409028",
          "suplier": "Reece",
          "description": " Plastec Pvc Combination P&S Trap 50mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405875",
          "suplier": "Reece",
          "description": " Dwv Floor Flange 50mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1404100",
          "suplier": "Reece",
          "description": " Dwv Junction 50 X 45 Deg Plain 1.00 EA ",
          "class": 1,
          "min": 8,
          "max": 16,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1013709",
          "suplier": "Reece",
          "description": " Fitquik Dual Isolation Stop With Swivel 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403710",
          "suplier": "Reece",
          "description": " Dwv Bend 50 X 45 Deg (42deg) M&F 1.00 EA ",
          "class": 1,
          "min": 8,
          "max": 16,
          "place": 0,
          "price": 0
        },
        {
          "code": " 605250 ",
          "suplier": "Reece",
          "description": "Comp Elbow Flared 15c X 15c 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 415960 ",
          "suplier": "Reece",
          "description": "Nylon Olive Elbow 15fi X 15c 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 606020 ",
          "suplier": "Reece",
          "description": "Comp Flared Tee Tut 15c 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1400110",
          "suplier": "Reece",
          "description": " Dwv Pvc Pipe 50mm X 6mtr 1.00 LEN",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1903694",
          "suplier": "Reece",
          "description": " Bridgland Grey Ptfe Tape 12mm X 10mtr 1.00 ROLL ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 2500273",
          "suplier": "Reece",
          "description": " T/Point Adaptor R1/2 M X 1/2 Saem & Nut 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1702035",
          "suplier": "Reece",
          "description": " Cover Plate 15mm Copper X Flat S/Steel 1.00 EA ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403110",
          "suplier": "Reece",
          "description": " Dwv Bend 50 X 45 Deg Plain 1.00 EA ",
          "class": 1,
          "min": 8,
          "max": 16,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1004190",
          "suplier": "Reece",
          "description": " Dura Brass Water Ball Valve F&F 15mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 107580 ",
          "suplier": "Reece",
          "description": "Dura Eagle Gas Cock (CXC) 15mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 2500542",
          "suplier": "Reece",
          "description": " Rego Twin Stage Reg W/Mco 250mj 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 605065 ",
          "suplier": "Reece",
          "description": "Comp Elbow Flared 15fi X 15c 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 107678 ",
          "suplier": "Reece",
          "description": "S/S Gas 8mm P/Tail Hwxinvert FL 450mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1031368",
          "suplier": "Reece",
          "description": " Austworld Gas Valv Loose Nut/Flr 20x15mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1407095",
          "suplier": "Reece",
          "description": " Dwv Pvc Flap Valve 50mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 604170 ",
          "suplier": "Reece",
          "description": "Comp Union Flared 15fi X 15c 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 207915 ",
          "suplier": "Reece",
          "description": "Brass Elbow M & F 15mm 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1031370",
          "suplier": "Reece",
          "description": " Austworld Wat Valv Loose Nut/Olv 20x15mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403805",
          "suplier": "Reece",
          "description": " Dwv Straight Coupling (Socket) 40mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403715",
          "suplier": "Reece",
          "description": " Dwv Bend 50 X 85 Deg M&F 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 208560 ",
          "suplier": "Reece",
          "description": "Brass Hex Nipple Reducing 20mm X 15mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 415995 ",
          "suplier": "Reece",
          "description": "Nylon Olive Union 15c X 15c 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 802860 ",
          "suplier": "Reece",
          "description": "Kembla (1/2\") 15mm Kemlag Sheath 1000mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1120088",
          "suplier": "Reece",
          "description": " Fitquik Washing Machine Stop Swivel Nut 1.00 EA ",
          "class": 1,
          "min": 6,
          "max": 12,
          "place": 0,
          "price": 0
        },
        {
          "code": " 602670 ",
          "suplier": "Reece",
          "description": "Comp Union Flared 15mi X 15c 1.00 EA ",
          "class": 1,
          "min": 10,
          "max": 20,
          "place": 0,
          "price": 0
        },
        {
          "code": " 416055 ",
          "suplier": "Reece",
          "description": "Nylon Olive Union 20fi X 15c 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 800320 ",
          "suplier": "Reece",
          "description": "Kembla Ann CU (1/2\") 15x091x 18m-Kemlag 1.00 COIL ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403810",
          "suplier": "Reece",
          "description": " Dwv Straight Coupling (Socket) 50mm 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 500422 ",
          "suplier": "Reece",
          "description": "Abey Hng F/Shank Clip 50x450 For Pvc(20) 1.00 BOX ",
          "class": 1,
          "min": 20,
          "max": 40,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1409135",
          "suplier": "Reece",
          "description": " Dura Trap Adapter 40fi X 50mi 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 2263197",
          "suplier": "Reece",
          "description": " Mizu Drift Uni Dn40 Pop UP P&W Chrome 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1537792",
          "suplier": "Reece",
          "description": " Evopex Pipe Pex 100 Dark Char 16mmx100mt 1.00 COIL ",
          "class": 1,
          "min": 2,
          "max": 4,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405650",
          "suplier": "Reece",
          "description": " Dwv Coupling (Connector) 50mm MI 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405870",
          "suplier": "Reece",
          "description": " Dwv Floor Flange 40mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1702040",
          "suplier": "Reece",
          "description": " Cover Plate 15mm Cppr 9mm Rise SS 1.00 EA ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 510885 ",
          "suplier": "Reece",
          "description": "S/Back Pex Clip W/Tab 16mm Tw/Nail (100) 1.00 PACK ",
          "class": 1,
          "min": 100,
          "max": 200,
          "place": 0,
          "price": 0
        },
        {
          "code": " 9800001",
          "suplier": "Reece",
          "description": " Ardent Ann CU (1/2) 15x091x18m-Pln (B) 1.00 COIL ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405610",
          "suplier": "Reece",
          "description": " Dwv Coupling (Connector) 50mm FI 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 604600 ",
          "suplier": "Reece",
          "description": "Comp Union Flared 15c X 15c 1.00 EA ",
          "class": 1,
          "min": 5,
          "max": 10,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1404859",
          "suplier": "Reece",
          "description": " Dwv Pipe Reducer 50 X 40mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1702030",
          "suplier": "Reece",
          "description": " Cover Plate 15mm Bsp X Flat S/S 50 1.00 PACK ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405510",
          "suplier": "Reece",
          "description": " Dwv Adaptor Pvc X MI 50mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1409270",
          "suplier": "Reece",
          "description": " Pvc Adjustable Trap Extension 50mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403125",
          "suplier": "Reece",
          "description": " Dwv Bend 50 X 85 Deg IO 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1842895",
          "suplier": "Reece",
          "description": " Performa Mixer Tap Extension Hose 150mm 1.00 PR ",
          "class": 1,
          "min": 2,
          "max": 4,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1702324",
          "suplier": "Reece",
          "description": " Blank Sheet Pvc Cover Plate 297mmx210mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1409682",
          "suplier": "Reece",
          "description": " Flexidinger Shower Conn Adj Brass Chrome 1.00 EA ",
          "class": 1,
          "min": 2,
          "max": 4,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1403030",
          "suplier": "Reece",
          "description": " Dwv Bend 40 X 85 Deg Plain 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1320030",
          "suplier": "Reece",
          "description": " Test Point Adaptor 1/2\" Bsp Female 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1400105",
          "suplier": "Reece",
          "description": " Dwv Pvc Pipe 40mm X 6mtr 1.00 LEN ",
          "class": 1,
          "min": 1,
          "max": 2,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1405455",
          "suplier": "Reece",
          "description": " Dwv Push ON Cap 50mm 1.00 EA ",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1409116",
          "suplier": "Reece",
          "description": " Dura Std Combination S&P Trap 40mm 1.00 EA ",
          "class": 1,
          "min": 2,
          "max": 4,
          "place": 0,
          "price": 0
        },
        {
          "code": " 1702010",
          "suplier": "Reece",
          "description": " Cover Plate 15mm Bsp X 10mm Rise S/S 50 1.00 PACK ",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": " 506243 ",
          "suplier": "Reece",
          "description": "Quickclip 16mm Pex Metal Tek Screw Qxtk2 1.00 BAG",
          "class": 1,
          "min": 50,
          "max": 100,
          "place": 0,
          "price": 0
        },
        {
          "code": 1405530,
          "suplier": "Reece",
          "description": "Dwv Adaptor Pvc X FI 50mm",
          "class": 1,
          "min": 3,
          "max": 6,
          "place": 0,
          "price": 0
        }
      ]
      )
  }
}
